# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

steps:

- task: DockerCompose@0
  displayName: Run Services
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run services'

- task: DockerCompose@0
  displayName: Build Services
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Assinatura do Azure 1(878b9867-d33c-46f5-8f57-d3dadbbcb302)'
    azureContainerRegistry: '{"loginServer":"geoareas.azurecr.io", "id" : "/subscriptions/878b9867-d33c-46f5-8f57-d3dadbbcb302/resourceGroups/Geral/providers/Microsoft.ContainerRegistry/registries/geoareas"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'


- task: DockerCompose@0
  displayName: Push Services
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Assinatura do Azure 1(878b9867-d33c-46f5-8f57-d3dadbbcb302)'
    azureContainerRegistry: '{"loginServer":"geoareas.azurecr.io", "id" : "/subscriptions/878b9867-d33c-46f5-8f57-d3dadbbcb302/resourceGroups/Geral/providers/Microsoft.ContainerRegistry/registries/geoareas"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
